### ISSUE TITLE
 DEF_CONFIG path

### ISSUE THREAD

**Issue by rmc0** [e-zk/shlog#3]
**DEF_CONFIG="${XDG_CONFIG_HOME:-${HOME}/.config}/shlog/shlog.conf"**

return : `shlog: error: cannot load config.`

XDG_CONFIG_HOME don't seem set on VOIDLINUX

but if I change it to **DEF_CONFIG="${HOME}/.config/shlog/shlog.conf"**

**Comment by e-zk** [comment]
If `XDG_CONFIG_HOME` is unset it _should_ be defaulting to `${HOME}/.config/shlog/shlog.conf`. Testing in a shell I see:

```console
$ unset XDG_CONFIG_HOME
$ echo "${XDG_CONFIG_HOME:-${HOME}/.config}/shlog/shlog.conf"
/home/zzz/.config/shlog/shlog.conf
```
Which means as far as I can tell it should be working correctly.  
I will look more into this.

**Comment by rmc0** [comment]
I don't understand but now it's ok

**Comment by e-zk** [comment]
Working now?  
That is strange. Perhaps it was broken in between commits and you happened to be using a bugged version?
