### ISSUE TITLE
double path 

### ISSUE THREAD

**Issue by rmc0** [e-zk/shlog#4]
`110          for post in ${site_root}/${posts_dir}/*.html; do`
`
122          for post in ${site_root}/${posts_dir}/*.md; do`

**# directory containing posts
posts_dir=${site_root}/posts**

so` ${site_root} ` need to be remove, I guess

**Comment by e-zk** [comment]
Nice catch!

Should be fixed by 39ca8a217dda78f5de1f49769018b0f428073133
